### ISSUE TITLE
what about 3D ?

### ISSUE THREAD

**Issue by ireneb612** [TheTempAccount/Co-Speech-Motion-Generation#2]
Do you think there is a way to convert the keypoints to 3d?

**Comment by TheTempAccount** [comment]
I don't know. There are some algorithms that convert 2D key points to 3D, but the results are not very good especially on fingers. I haven't found a satisfying method to get 3D annotations from videos.

**Comment by MengHao666** [comment]
> 

Hi, have you tried to get 3D results(3d keypoints or 3D transform) ? I also want to lift the algorithom into 3d level? Do you have some suggestions?
