### ISSUE TITLE
how to get correspondence between key point index and its name?

### ISSUE THREAD

**Issue by animebing** [TheTempAccount/Co-Speech-Motion-Generation#4]
Thanks for your great work. In the visualization part of the inference code, key points are connected by edges, but how to get the key point name for each index?

**Comment by TheTempAccount** [comment]
The key point definition is from https://cmu-perceptual-computing-lab.github.io/openpose/web/html/doc/md_doc_02_output.html#pose-output-format-body_25

**Comment by animebing** [comment]
@TheTempAccount Thanks for your quick response, it helps me a lot
