### ISSUE TITLE
Is the speech text necessary during inference?

### ISSUE THREAD

**Issue by HaozhouPang** [TheTempAccount/Co-Speech-Motion-Generation#5]
Hello, 

Thanks for posting this awesome work! 

I am wondering that, in the given 'sample_audio' folder, the wav file is paired with .TextGrid file (generated from mfa aligner), and the speech text is used to generate the label which indicates whether there is a pose mode change or not in that second. 

What if I want to test the model with my own wav file which does not come with the paired text file? Did you use some ASR model to get the speech text?

Thanks,
Haozhou.

**Comment by TheTempAccount** [comment]
I use DeepSpeech for speech recognition, and use mfa to align. But the text files generated by DeepSpeech have many mistakes.
The TextGrid is used to get the binary label sequence and the number of generation steps. You can try manually specify these such as set the binary sequence to all zeros or all ones.

**Comment by HaozhouPang** [comment]
Thanks for the quick response!

Would manually specifying binary sequence to all zeros or ones cause performance degeneration? Would all-zero sequence cause the output becomes "Flat"? I think if the binary sequence is all zeros, then the pose mode will not change, and only rhythmic dynamics would influence the output?

**Comment by TheTempAccount** [comment]
Yes, it may produce less appealing results on some cases. So it is better to use a paired text file.
